apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-f1742471050353
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-f1742471050353
  name: chatbot-f1742471050353
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
