apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-f1742471050353
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-f1742471050353
  name: chatbot-f1742471050353
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: chatbot-f1742471050353
